name: Prod CI/CD

on:
  push:
    branches: [production]

env:
  BRANCH_NAME: production
  DOCKER_IMAGE: sookyeong/bk-nutrition-front
  DOCKER_NAME: bk-nutrition-front-production

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - env:
          ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: |
          echo "$ENV_FILE" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:production
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # docker_pull_on_server:
  #   needs: docker_build_and_push
  #   runs-on: [self-hosted, BK-Nutrition-production]
  #   steps:
  #     - name: Deploy
  #       run: |
  #         docker stop bk-nutrition-front-production && docker rm bk-nutrition-front-production
  #         docker system prune -a -f
  #         docker pull sookyeong/bk-nutrition-front:production
  #         docker run -d -p 3000:3000 --name bk-nutrition-front-production --restart always sookyeong/bk-nutrition-front:production
